/**
 * Texture path map + cached, resolution-tiered loading.
 *
 * Three tiers of the same images ship:
 *
 *   lo    /textures/lo/<key>.webp    <= 2048 px   ~4 MB for the whole set
 *   mid   /textures/mid/<key>.webp   <= 4096 px   ~15 MB
 *   hi    /textures/<stem>.jpg                    native, up to 8192 px, ~51 MB
 *
 * `lo` and `mid` are generated by scripts/build-texture-tiers.mjs from the very
 * files `hi` serves, so a tier is never a different image — only a smaller one.
 *
 * Why tiers exist
 * ---------------
 * The intro is the loading screen, so whatever the boot path asks for is decoded
 * and uploaded *while the cinematic is playing*. An 8192x4096 map is 134 MB of
 * decoded RGBA, a synchronous `texImage2D`, and a `glGenerateMipmap` — on
 * integrated graphics, a stall of a couple hundred milliseconds each. Nine of
 * them land across the detonation. Nothing on screen at that moment can resolve
 * even 2K (Earth is a few hundred pixels tall, Mercury is a dot), so the whole
 * sequence runs on `lo` and the resolution is raised afterwards, by `upgrade()`,
 * when a hitch lands on a static camera instead of on the shot.
 *
 * Upgrading mutates the EXISTING THREE.Texture rather than handing back a new
 * one: every material already holds a reference to it, so swapping `image` and
 * flagging `needsUpdate` re-uploads in place with nothing to rebind.
 */
import * as THREE from 'three'
import type { BodyId } from '../data/bodies'

/** Resolution tier. Ordered — `TIER_ORDER` below depends on it. */
export type TextureRes = 'lo' | 'mid' | 'hi'

export const TIER_ORDER: TextureRes[] = ['lo', 'mid', 'hi']

export function isHigherTier(a: TextureRes, b: TextureRes): boolean {
  return TIER_ORDER.indexOf(a) > TIER_ORDER.indexOf(b)
}

/** One key to raise to one tier. Consumed by TextureUpgrader. */
export interface UpgradeJob {
  key: string
  res: TextureRes
}

/**
 * Candidate stems per logical key, for the `hi` tier only.
 * Tried in order .jpg -> .png -> .webp so a native JPEG wins over a WebP
 * sitting beside it. One stem per key — unused 2k_* / alias files are gone.
 */
const TEXTURE_CANDIDATES: Record<string, string[]> = {
  sun: ['sun'],
  mercury: ['mercury'],
  venus: ['venus'],
  venus_atmosphere: ['venus_atmosphere'],
  earth: ['earth'],
  earth_night: ['earth_night'],
  earth_clouds: ['earth_clouds'],
  earth_normal: ['earth_normal'],
  earth_specular: ['earth_specular'],
  mars: ['mars'],
  mars_normal: ['mars_normal'],
  jupiter: ['jupiter'],
  saturn: ['saturn'],
  saturn_ring: ['saturn_ring'],
  uranus: ['uranus'],
  neptune: ['neptune'],
  moon: ['moon'],
  stars: ['stars'],
}

export const CRITICAL_TEXTURE_KEYS = [
  'stars',
  'sun',
  'earth',
  'earth_night',
  'earth_clouds',
  'earth_normal',
  'earth_specular',
] as const

/** Every auxiliary map a body pulls in beyond its own albedo. */
const COMPANION_KEYS: Partial<Record<BodyId, string[]>> = {
  earth: ['earth_night', 'earth_clouds', 'earth_normal', 'earth_specular'],
  mars: ['mars_normal'],
  venus: ['venus_atmosphere'],
  saturn: ['saturn_ring'],
}

/**
 * Maps a viewer reads as the surface itself, so they carry the device's full
 * ceiling. Everything not listed here — cloud sheets, normal and specular data,
 * the Venusian haze, Saturn's ring strip — is either low-frequency or drawn
 * semi-transparent over something else, and is held a tier lower. That single
 * distinction is what keeps Earth's five maps inside a sane memory budget.
 */
const SECONDARY_KEYS = new Set([
  'earth_clouds',
  'earth_normal',
  'earth_specular',
  'mars_normal',
  'venus_atmosphere',
  'saturn_ring',
])

export function bodyTextureKey(id: BodyId): string {
  return id
}

/** Every texture key a body's materials sample, albedo first. */
export function bodyTextureKeys(id: BodyId): string[] {
  return [bodyTextureKey(id), ...(COMPANION_KEYS[id] ?? [])]
}

/** True when `key` is a surface the viewer looks at rather than a modifier. */
export function isPrimaryKey(key: string): boolean {
  return !SECONDARY_KEYS.has(key)
}

function candidateUrls(key: string, res: TextureRes): string[] {
  if (res !== 'hi') return [`/textures/${res}/${key}.webp`]

  const stems = TEXTURE_CANDIDATES[key]
  if (!stems) throw new Error(`Unknown texture key: ${key}`)
  const urls: string[] = []
  for (const stem of stems) {
    urls.push(
      `/textures/${stem}.jpg`,
      `/textures/${stem}.png`,
      `/textures/${stem}.webp`,
    )
  }
  return urls
}

type TextureImage = HTMLImageElement | ImageBitmap

interface Entry {
  texture: THREE.Texture
  res: TextureRes
  colorSpace: THREE.ColorSpace
  /** In-flight upgrade, so two callers cannot race the same key upward. */
  upgrading: Promise<void> | null
}

export class TextureCache {
  private loader = new THREE.TextureLoader()
  private bitmapLoader = createBitmapLoader()
  private pending = new Map<string, Promise<THREE.Texture>>()
  private entries = new Map<string, Entry>()
  private maxAniso = 16
  private renderer: THREE.WebGLRenderer | null = null
  /** Serialises GPU uploads to one per frame. See `scheduleUpload`. */
  private uploads: Promise<void> = Promise.resolve()

  setMaxAnisotropy(n: number): void {
    this.maxAniso = Math.max(1, n)
  }

  /**
   * Handing the cache a renderer lets `upgrade()` force the GPU upload at a
   * moment of its choosing via `initTexture`. Without it the upload happens
   * inside the next `render()` — the one place we are trying to keep clear.
   */
  useRenderer(renderer: THREE.WebGLRenderer): void {
    this.renderer = renderer
  }

  getSync(key: string): THREE.Texture | null {
    return this.entries.get(key)?.texture ?? null
  }

  /** Tier a key is currently resolved at, or null if it never loaded. */
  resolutionOf(key: string): TextureRes | null {
    return this.entries.get(key)?.res ?? null
  }

  /** Every key that has resolved, in load order. */
  loadedKeys(): string[] {
    return [...this.entries.keys()]
  }

  load(
    key: string,
    opts?: { colorSpace?: THREE.ColorSpace },
  ): Promise<THREE.Texture> {
    const existing = this.entries.get(key)
    if (existing) return Promise.resolve(existing.texture)
    const hit = this.pending.get(key)
    if (hit) return hit

    const colorSpace = opts?.colorSpace ?? THREE.SRGBColorSpace
    // Everything enters at `lo`, always — including maps requested long after
    // boot. A body appears the moment its 2K map lands and sharpens a beat later
    // under `upgrade()`, which is both faster to first paint and the only way to
    // keep the resolution decision in one place.
    const res: TextureRes = 'lo'

    const promise = this.loadImage(key, res)
      .then((image) => {
        const texture = new THREE.Texture(image as HTMLImageElement)
        // ImageBitmaps are decoded pre-flipped (see `createBitmapLoader`), so the
        // driver must not flip them a second time. The two paths therefore
        // disagree on `flipY` and agree on the result.
        texture.flipY = !(
          typeof ImageBitmap !== 'undefined' && image instanceof ImageBitmap
        )
        this.configure(texture, colorSpace)
        texture.needsUpdate = true
        this.scheduleUpload(texture)

        this.entries.set(key, { texture, res, colorSpace, upgrading: null })
        this.pending.delete(key)
        return texture
      })
      .catch((err) => {
        this.pending.delete(key)
        throw err
      })

    this.pending.set(key, promise)
    return promise
  }

  loadData(key: string): Promise<THREE.Texture> {
    return this.load(key, { colorSpace: THREE.NoColorSpace })
  }

  /**
   * Raise one already-loaded key to a higher tier, in place.
   *
   * Resolves once the new image is on the GPU, so a caller stepping through a
   * list of keys spreads the uploads over as many frames as there are keys
   * rather than stacking them into one.
   */
  async upgrade(key: string, res: TextureRes): Promise<void> {
    // A travel prefetch and its upgrade are requested in the same tick, so the
    // 2K load is usually still in flight here. Waiting for it is what keeps the
    // upgrade from being silently dropped for a key that is about to exist.
    const inFlight = this.pending.get(key)
    if (inFlight) await inFlight.catch(() => undefined)

    const entry = this.entries.get(key)
    if (!entry) return
    if (!isHigherTier(res, entry.res)) return
    if (entry.upgrading) return entry.upgrading

    const job = this.loadImage(key, res)
      .then((image) => {
        // Re-read: `res` may have been overtaken while the fetch was in flight.
        if (!isHigherTier(res, entry.res)) return
        const previous = entry.texture.image as TextureImage | undefined
        entry.texture.image = image
        entry.texture.flipY = !(
          typeof ImageBitmap !== 'undefined' && image instanceof ImageBitmap
        )
        this.configure(entry.texture, entry.colorSpace)
        // Bumps the source version, so the next upload replaces the old level
        // and regenerates the mip chain from the new one.
        entry.texture.needsUpdate = true
        entry.res = res
        // Do the expensive part HERE rather than letting it fall into the next
        // render, which is what makes the hitch schedulable.
        this.renderer?.initTexture(entry.texture)
        if (previous instanceof ImageBitmap) previous.close()
      })
      .catch(() => undefined)
      .finally(() => {
        entry.upgrading = null
      })

    entry.upgrading = job
    return job
  }

  /**
   * Push one texture to the GPU, at most one per animation frame.
   *
   * Two problems, one queue. Left entirely alone, a `texImage2D` +
   * `glGenerateMipmap` pair does not happen when the image arrives — it happens
   * on the first frame that draws a material using it, so ten maps that trickled
   * in over a second all upload on the SAME frame, and the sequence puts that
   * frame at the detonation. Uploading eagerly on arrival fixes the *where* and
   * not the *how many*: over a fast connection all ten still resolve inside a few
   * hundred milliseconds and pile into a handful of frames.
   *
   * Chaining through `requestAnimationFrame` fixes both. Each upload waits for
   * the frame after the one before it, so the cost is a known constant per frame
   * instead of an unbounded pile-up, and during the intro these land in the
   * opening void — seventeen draw calls and a nearly black screen — rather than
   * on the busiest frame in the sequence.
   */
  private scheduleUpload(texture: THREE.Texture): void {
    if (!this.renderer || typeof requestAnimationFrame !== 'function') return
    this.uploads = this.uploads.then(
      () =>
        new Promise<void>((resolve) => {
          requestAnimationFrame(() => {
            try {
              this.renderer?.initTexture(texture)
            } catch {
              // An upload that fails here just happens later, inside render().
            }
            resolve()
          })
        }),
    )
  }

  private configure(texture: THREE.Texture, colorSpace: THREE.ColorSpace): void {
    texture.colorSpace = colorSpace
    texture.anisotropy = this.maxAniso
    texture.minFilter = THREE.LinearMipmapLinearFilter
    texture.magFilter = THREE.LinearFilter
    texture.generateMipmaps = true
  }

  private async loadImage(key: string, res: TextureRes): Promise<TextureImage> {
    const bitmap = this.bitmapLoader && (await bitmapFlipIsHonoured())
      ? this.bitmapLoader
      : null
    const urls = candidateUrls(key, res)

    return new Promise((resolve, reject) => {
      const tryAt = (i: number): void => {
        if (i >= urls.length) {
          reject(new Error(`No texture found for key: ${key} @ ${res}`))
          return
        }
        const next = (): void => tryAt(i + 1)
        if (bitmap) {
          bitmap.load(urls[i], resolve as (b: ImageBitmap) => void, undefined, next)
        } else {
          this.loader.load(
            urls[i],
            (tex) => resolve(tex.image as HTMLImageElement),
            undefined,
            next,
          )
        }
      }
      tryAt(0)
    })
  }

  async loadCritical(): Promise<void> {
    await Promise.all(
      CRITICAL_TEXTURE_KEYS.map((k) =>
        k === 'earth_normal' || k === 'earth_specular'
          ? this.loadData(k).catch(() => undefined)
          : this.load(k).catch(() => undefined),
      ),
    )
  }

  async loadBody(id: BodyId): Promise<THREE.Texture> {
    return this.load(bodyTextureKey(id))
  }

  async loadAllBodies(ids: BodyId[]): Promise<void> {
    await Promise.all(ids.map((id) => this.loadBody(id).catch(() => undefined)))
  }
}

/**
 * `createImageBitmap` moves JPEG/WebP decode off the main thread, which is the
 * difference between a 4096x2048 map costing a frame and costing nothing. Null
 * where the API is missing, and the caller falls back to `TextureLoader`.
 *
 * `imageOrientation: 'flipY'` bakes the flip into the bitmap so the upload never
 * depends on `UNPACK_FLIP_Y_WEBGL`, whose behaviour for ImageBitmap sources has
 * historically differed between browsers. Get this wrong and every planet is
 * upside down, so it is pinned rather than inferred.
 */
let flipProbe: Promise<boolean> | null = null

/**
 * Prove, once, that this browser honours `imageOrientation: 'flipY'`.
 *
 * The bitmap path deliberately does not rely on `UNPACK_FLIP_Y_WEBGL`, whose
 * treatment of ImageBitmap sources has differed between browsers — it bakes the
 * flip in at decode instead and turns `texture.flipY` off. If the option were
 * silently ignored, nothing would throw: every planet would simply render upside
 * down, on whichever browser ignores it, and nowhere else. That failure is too
 * quiet and too total to leave to a support table, so it is measured: a 1x2
 * blob, white over black, decoded through the same `createImageBitmap` call the
 * loader uses. Flip honoured means the black row comes back on top.
 */
function bitmapFlipIsHonoured(): Promise<boolean> {
  if (flipProbe) return flipProbe

  flipProbe = (async () => {
    if (typeof document === 'undefined' || typeof createImageBitmap === 'undefined') {
      return false
    }
    try {
      const source = document.createElement('canvas')
      source.width = 1
      source.height = 2
      const paint = source.getContext('2d')
      if (!paint) return false
      paint.fillStyle = '#ffffff'
      paint.fillRect(0, 0, 1, 1)
      paint.fillStyle = '#000000'
      paint.fillRect(0, 1, 1, 1)

      // Probe through a Blob rather than the canvas directly: that is the source
      // type ImageBitmapLoader actually feeds `createImageBitmap`, and it is the
      // one the orientation option is specified against.
      const blob = await new Promise<Blob | null>((resolve) =>
        source.toBlob(resolve, 'image/png'),
      )
      if (!blob) return false

      const bitmap = await createImageBitmap(blob, { imageOrientation: 'flipY' })
      const probe = document.createElement('canvas')
      probe.width = 1
      probe.height = 2
      const read = probe.getContext('2d', { willReadFrequently: true })
      if (!read) {
        bitmap.close()
        return false
      }
      read.drawImage(bitmap, 0, 0)
      const topLuma = read.getImageData(0, 0, 1, 1).data[0]
      bitmap.close()
      return topLuma < 128
    } catch {
      return false
    }
  })()

  return flipProbe
}

function createBitmapLoader(): THREE.ImageBitmapLoader | null {
  if (typeof createImageBitmap === 'undefined') return null
  try {
    const loader = new THREE.ImageBitmapLoader()
    loader.setOptions({
      imageOrientation: 'flipY',
      premultiplyAlpha: 'none',
      colorSpaceConversion: 'default',
    } as ImageBitmapOptions)
    return loader
  } catch {
    return null
  }
}

/** Fresnel atmosphere shell — soft limb glow. */
export function createAtmosphereMaterial(
  color: THREE.ColorRepresentation,
  intensity = 1,
): THREE.ShaderMaterial {
  const c = new THREE.Color(color)
  return new THREE.ShaderMaterial({
    uniforms: {
      glowColor: { value: c },
      coeficient: { value: 0.55 },
      power: { value: 3.4 * intensity },
    },
    vertexShader: /* glsl */ `
      varying vec3 vNormal;
      varying vec3 vWorldPos;
      void main() {
        vNormal = normalize(normalMatrix * normal);
        vec4 world = modelMatrix * vec4(position, 1.0);
        vWorldPos = world.xyz;
        gl_Position = projectionMatrix * viewMatrix * world;
      }
    `,
    fragmentShader: /* glsl */ `
      uniform vec3 glowColor;
      uniform float coeficient;
      uniform float power;
      varying vec3 vNormal;
      varying vec3 vWorldPos;
      void main() {
        vec3 viewDir = normalize(cameraPosition - vWorldPos);
        float intensity = pow(coeficient - dot(vNormal, viewDir), power);
        intensity = clamp(intensity, 0.0, 1.0);
        gl_FragColor = vec4(glowColor, intensity * 0.9);
      }
    `,
    side: THREE.FrontSide,
    blending: THREE.AdditiveBlending,
    transparent: true,
    depthWrite: false,
  })
}
