/**
 * Pure body catalog for the solar-system education explorer.
 * No DOM / WebGL — unit-testable educational truth source.
 */

export type BodyId =
  | 'sun'
  | 'mercury'
  | 'venus'
  | 'earth'
  | 'moon'
  | 'mars'
  | 'jupiter'
  | 'saturn'
  | 'uranus'
  | 'neptune'

export interface Hotspot {
  id: string
  label: string
  description: string
  /** Latitude in degrees (−90…90) for marker placement on the sphere */
  lat: number
  /** Longitude in degrees (−180…180) */
  lon: number
}

export interface BodyContent {
  id: BodyId
  name: string
  /** 0 = Sun, 1 = Mercury … 8 = Neptune. The Moon shares Earth's 3. */
  orderFromSun: number
  tagline: string
  facts: { label: string; value: string }[]
  overview: string
  composition: string
  notableFeatures: string[]
  hotspots: Hotspot[]
  textureKey: string
  hasRings?: boolean
  hasAtmosphere?: boolean
  hasClouds?: boolean
  /** Educational display radius (Earth ≈ 1). Gas giants scaled for readability. */
  displayRadius: number
  /** Compressed educational orbit distance for layout */
  orbitDistance: number
  /** Fallback color when texture is loading */
  color: string
  /** Emissive intensity for stars / glowing bodies */
  emissive?: number
}

/**
 * Bodies the app actually builds, in journey order.
 *
 * This is the single switch for what exists in the scene: the scene graph, the
 * planet labels, the journey rail, and the intro's launch list all iterate it.
 *
 * MOON DISABLED (2026-08-15, by request — "remove the moon for now").
 * Nothing about the Moon has been deleted: `BODIES.moon`, its educational
 * content, its texture entry, its orbital elements (`MOON_ORBIT`), its
 * earthshine material in `planets/moon.ts`, and `moonPositionAU` are all intact
 * and still unit-tested. Re-enabling is this one line plus the four call sites
 * marked `MOON DISABLED` in SolarSystem.ts, OrbitPaths.ts, IntroSequence.ts,
 * and main.ts.
 */
export const BODY_ORDER: BodyId[] = [
  'sun',
  'mercury',
  'venus',
  'earth',
  // 'moon',
  'mars',
  'jupiter',
  'saturn',
  'uranus',
  'neptune',
]

export const BODIES: Record<BodyId, BodyContent> = {
  sun: {
    id: 'sun',
    name: 'Sun',
    orderFromSun: 0,
    tagline: 'The star that powers our solar system',
    facts: [
      { label: 'Type', value: 'G-type main-sequence star (G2V)' },
      { label: 'Diameter', value: '~1.39 million km (109× Earth)' },
      { label: 'Mass', value: '1.989 × 10³⁰ kg (~333,000× Earth)' },
      { label: 'Surface temp', value: '~5,500 °C (photosphere)' },
      { label: 'Core temp', value: '~15 million °C' },
      { label: 'Age', value: '~4.6 billion years' },
      { label: 'Distance from Earth', value: '1 AU (~149.6 million km)' },
      { label: 'Composition', value: '~73% hydrogen, ~25% helium' },
    ],
    overview:
      'The Sun is a giant ball of plasma at the center of our solar system. Nuclear fusion in its core converts hydrogen into helium, releasing the energy that lights and warms the planets. Its gravity holds every planet, asteroid, and comet in orbit.',
    composition:
      'Primarily hydrogen and helium plasma, with trace heavier elements. Energy is generated by proton–proton chain fusion in the core and radiates outward through the radiative and convective zones to the photosphere.',
    notableFeatures: [
      'Solar flares and coronal mass ejections',
      'Sunspots — cooler magnetic regions on the photosphere',
      '11-year solar activity cycle',
      'Solar wind that shapes planetary magnetospheres',
    ],
    hotspots: [
      {
        id: 'sun-photosphere',
        label: 'Photosphere',
        description:
          'The visible “surface” of the Sun. Granulation patterns mark rising hot plasma and sinking cooler plasma.',
        lat: 12,
        lon: -40,
      },
      {
        id: 'sun-sunspot',
        label: 'Sunspot region',
        description:
          'Dark, cooler patches where intense magnetic fields suppress convection. Often the source of solar storms.',
        lat: -22,
        lon: 55,
      },
      {
        id: 'sun-corona',
        label: 'Corona zone',
        description:
          'The ultra-hot outer atmosphere, visible during total eclipses. Temperatures soar to millions of degrees.',
        lat: 48,
        lon: 120,
      },
      {
        id: 'sun-equator',
        label: 'Equatorial belt',
        description:
          'The equator rotates faster (~25 days) than the poles (~35 days) — differential rotation that twists magnetic fields.',
        lat: 5,
        lon: -100,
      },
    ],
    textureKey: 'sun',
    hasAtmosphere: false,
    // Still ~2.4x Earth's display radius so it reads as the largest body, but
    // small enough that Mercury's and Venus' orbits stay clear of it. (The real
    // ratio is 109x, which no single view can show alongside the outer planets.)
    displayRadius: 2.4,
    orbitDistance: 0,
    color: '#ffcc33',
    emissive: 1.2,
  },

  mercury: {
    id: 'mercury',
    name: 'Mercury',
    orderFromSun: 1,
    tagline: 'Scorched, cratered world closest to the Sun',
    facts: [
      { label: 'Diameter', value: '4,880 km (0.38× Earth)' },
      { label: 'Distance from Sun', value: '0.39 AU (~58 million km)' },
      { label: 'Day length', value: '176 Earth days (solar day)' },
      { label: 'Year length', value: '88 Earth days' },
      { label: 'Moons', value: 'None' },
      { label: 'Surface temp', value: '−180 °C to 430 °C' },
      { label: 'Atmosphere', value: 'Negligible exosphere' },
      { label: 'Gravity', value: '0.38 g' },
    ],
    overview:
      'Mercury is a dense, airless rocky planet with extremes of heat and cold. Its surface is scarred by ancient impacts. Despite being closest to the Sun, it is not the hottest planet — that title belongs to Venus — but dayside temperatures still melt lead.',
    composition:
      'Large iron-rich core (~85% of radius) with a thin silicate mantle and crust. Weak residual magnetic field suggests a partially molten core.',
    notableFeatures: [
      'Caloris Basin — huge impact crater ~1,550 km across',
      'Extreme temperature swings',
      '3:2 spin–orbit resonance',
      'Ice in permanently shadowed polar craters',
    ],
    hotspots: [
      {
        id: 'merc-caloris',
        label: 'Caloris Basin',
        description:
          'One of the largest impact basins in the solar system, formed by a colossal asteroid strike early in Mercury’s history.',
        lat: 30,
        lon: -170,
      },
      {
        id: 'merc-scarps',
        label: 'Lobate scarps',
        description:
          'Cliff-like ridges that formed as Mercury’s iron core cooled and the planet contracted over billions of years.',
        lat: -15,
        lon: 40,
      },
      {
        id: 'merc-poles',
        label: 'Polar ice',
        description:
          'Despite scorching days, radar and MESSENGER data show water ice in craters that never see sunlight.',
        lat: 82,
        lon: 0,
      },
    ],
    textureKey: 'mercury',
    displayRadius: 0.55,
    orbitDistance: 6,
    color: '#9e9e9e',
  },

  venus: {
    id: 'venus',
    name: 'Venus',
    orderFromSun: 2,
    tagline: 'Earth’s toxic twin with a runaway greenhouse',
    facts: [
      { label: 'Diameter', value: '12,104 km (0.95× Earth)' },
      { label: 'Distance from Sun', value: '0.72 AU (~108 million km)' },
      { label: 'Day length', value: '243 Earth days (retrograde)' },
      { label: 'Year length', value: '225 Earth days' },
      { label: 'Moons', value: 'None' },
      { label: 'Surface temp', value: '~465 °C (hottest planet)' },
      { label: 'Atmosphere', value: 'CO₂ with sulfuric acid clouds' },
      { label: 'Pressure', value: '~92× Earth sea level' },
    ],
    overview:
      'Venus is nearly Earth-sized but wrapped in a crushing carbon-dioxide atmosphere that traps heat. Surface temperatures are hot enough to melt lead, and sulfuric acid clouds rain in the upper atmosphere. It spins slowly backwards compared to most planets.',
    composition:
      'Rocky silicate body with iron core. Thick CO₂ atmosphere (~96.5%) and opaque sulfuric acid cloud decks hide the surface from ordinary optical telescopes.',
    notableFeatures: [
      'Runaway greenhouse effect',
      'Retrograde rotation',
      'Volcanic plains and coronae',
      'Maxwell Montes — tallest mountain on Venus',
    ],
    hotspots: [
      {
        id: 'ven-maxwell',
        label: 'Maxwell Montes',
        description:
          'The highest mountain range on Venus, rising ~11 km — higher than Everest — in the Ishtar Terra highland.',
        lat: 65,
        lon: 5,
      },
      {
        id: 'ven-clouds',
        label: 'Acid cloud deck',
        description:
          'Dense sulfuric acid clouds reflect sunlight, making Venus the brightest planet in Earth’s sky.',
        lat: 10,
        lon: -80,
      },
      {
        id: 'ven-volcanism',
        label: 'Volcanic plains',
        description:
          'Radar maps show vast lava plains and shield volcanoes; Venus may still be geologically active.',
        lat: -25,
        lon: 140,
      },
    ],
    textureKey: 'venus',
    hasAtmosphere: true,
    displayRadius: 0.95,
    orbitDistance: 9,
    color: '#e8c47a',
  },

  earth: {
    id: 'earth',
    name: 'Earth',
    orderFromSun: 3,
    tagline: 'Our living blue planet — the only known home of life',
    facts: [
      { label: 'Diameter', value: '12,742 km' },
      { label: 'Distance from Sun', value: '1 AU (~149.6 million km)' },
      { label: 'Day length', value: '23 h 56 min (sidereal)' },
      { label: 'Year length', value: '365.25 days' },
      { label: 'Moons', value: '1 (the Moon)' },
      { label: 'Surface temp', value: 'Average ~15 °C' },
      { label: 'Atmosphere', value: '78% N₂, 21% O₂, trace gases' },
      { label: 'Water', value: '~71% of surface covered by oceans' },
    ],
    overview:
      'Earth is the only planet known to host life. Liquid water oceans, a protective magnetic field, an oxygen-rich atmosphere, and a climate in the habitable zone make it unique. Plate tectonics recycle the crust and regulate the long-term carbon cycle.',
    composition:
      'Layered rocky planet: iron–nickel core, silicate mantle, thin crust. Dynamic hydrosphere and biosphere reshape the surface continuously.',
    notableFeatures: [
      'Liquid water oceans',
      'Active plate tectonics',
      'Oxygen-rich atmosphere and ozone layer',
      'Strong magnetic field (magnetosphere)',
      'Diverse climates and ecosystems',
    ],
    hotspots: [
      {
        id: 'earth-oceans',
        label: 'Pacific Ocean',
        description:
          'Earth’s largest ocean holds more than half of all seawater and drives global climate through heat transport and storms.',
        lat: 0,
        lon: -150,
      },
      {
        id: 'earth-himalayas',
        label: 'Himalayas',
        description:
          'The world’s highest mountain range, raised by the ongoing collision of the Indian and Eurasian tectonic plates.',
        lat: 28,
        lon: 85,
      },
      {
        id: 'earth-amazon',
        label: 'Amazon Basin',
        description:
          'The largest tropical rainforest on Earth — a biodiversity hotspot and major player in the global carbon and water cycles.',
        lat: -5,
        lon: -60,
      },
      {
        id: 'earth-antarctica',
        label: 'Antarctica',
        description:
          'The frozen continent stores ~60% of Earth’s fresh water as ice and strongly influences ocean circulation and sea level.',
        lat: -80,
        lon: 0,
      },
    ],
    textureKey: 'earth',
    hasAtmosphere: true,
    hasClouds: true,
    displayRadius: 1,
    orbitDistance: 12,
    color: '#3d7ee8',
  },

  moon: {
    id: 'moon',
    name: 'Moon',
    orderFromSun: 3,
    tagline: 'Earth’s tidally locked companion — the only world humans have walked',
    facts: [
      { label: 'Diameter', value: '3,475 km (0.27× Earth)' },
      { label: 'Distance from Earth', value: '~384,400 km (0.00257 AU)' },
      { label: 'Day length', value: '27.3 Earth days (tidally locked)' },
      { label: 'Orbital period', value: '27.3 Earth days (sidereal month)' },
      { label: 'Synodic month', value: '29.5 days (new moon to new moon)' },
      { label: 'Surface temp', value: '−173 °C to 127 °C' },
      { label: 'Gravity', value: '0.165 g' },
      { label: 'Atmosphere', value: 'Negligible collisionless exosphere' },
    ],
    overview:
      'The Moon is Earth’s only natural satellite and the largest moon relative to its planet in the solar system. It is tidally locked, so the same face always points toward us, while a small optical libration lets us see about 59% of the surface over time. Its pull raises the tides and steadily slows Earth’s spin.',
    composition:
      'Anorthositic highlands and basaltic maria over a small iron-rich core. The crust is thicker on the far side. No global magnetic field and almost no atmosphere leave the surface scarred by billions of years of impacts.',
    notableFeatures: [
      'Tidally locked 1:1 spin–orbit resonance',
      'Dark maria — ancient flood basalts',
      'South Pole–Aitken Basin, one of the largest impact structures known',
      'Apollo and robotic landing sites',
      'Orbit inclined 5.15° to the ecliptic',
    ],
    hotspots: [
      {
        id: 'moon-tycho',
        label: 'Tycho crater',
        description:
          'A young, 85 km impact crater whose bright ray system stretches across much of the near side — a landmark even in small telescopes.',
        lat: -43.3,
        lon: -11.2,
      },
      {
        id: 'moon-imbrium',
        label: 'Mare Imbrium',
        description:
          'The Sea of Rains: a vast basaltic plain filling a 1,200 km impact basin, one of the dark “seas” that sketch the Man in the Moon.',
        lat: 32.8,
        lon: -15.6,
      },
      {
        id: 'moon-apollo11',
        label: 'Sea of Tranquility',
        description:
          'Mare Tranquillitatis — landing region of Apollo 11 in 1969, where humans first walked on another world.',
        lat: 0.7,
        lon: 23.5,
      },
      {
        id: 'moon-spa',
        label: 'South Pole–Aitken',
        description:
          'A ~2,500 km far-side/south-polar basin, among the largest and oldest impact structures in the solar system. Permanently shadowed craters may hold water ice.',
        lat: -53,
        lon: -169,
      },
    ],
    textureKey: 'moon',
    displayRadius: 0.273,
    orbitDistance: 12.4,
    color: '#c9c3b6',
  },

  mars: {
    id: 'mars',
    name: 'Mars',
    orderFromSun: 4,
    tagline: 'The red planet of ancient rivers and giant volcanoes',
    facts: [
      { label: 'Diameter', value: '6,779 km (0.53× Earth)' },
      { label: 'Distance from Sun', value: '1.52 AU (~228 million km)' },
      { label: 'Day length', value: '24 h 37 min (a “sol”)' },
      { label: 'Year length', value: '687 Earth days' },
      { label: 'Moons', value: '2 (Phobos & Deimos)' },
      { label: 'Surface temp', value: 'Average ~−60 °C' },
      { label: 'Atmosphere', value: 'Thin CO₂ (~1% of Earth pressure)' },
      { label: 'Gravity', value: '0.38 g' },
    ],
    overview:
      'Mars is a cold desert world with polar ice caps, the tallest volcano, and the longest canyon in the solar system. Evidence of ancient rivers and lakes suggests it was once wetter. Rovers and orbiters continue to search for signs of past life.',
    composition:
      'Rocky planet with iron core, basaltic crust rich in iron oxides (the red rust). Thin atmosphere and no global magnetic field leave the surface exposed to solar wind and radiation.',
    notableFeatures: [
      'Olympus Mons — tallest volcano (~22 km)',
      'Valles Marineris — canyon system ~4,000 km long',
      'Polar ice caps (water + CO₂ ice)',
      'Evidence of ancient liquid water',
    ],
    hotspots: [
      {
        id: 'mars-olympus',
        label: 'Olympus Mons',
        description:
          'A shield volcano nearly three times the height of Everest and about as wide as France — the tallest planetary mountain known.',
        lat: 18,
        lon: -133,
      },
      {
        id: 'mars-valles',
        label: 'Valles Marineris',
        description:
          'A vast canyon system stretching a quarter of the way around Mars — far deeper and longer than the Grand Canyon.',
        lat: -10,
        lon: -70,
      },
      {
        id: 'mars-poles',
        label: 'North polar cap',
        description:
          'Layered deposits of water ice and frozen carbon dioxide that expand and shrink with the seasons.',
        lat: 85,
        lon: 0,
      },
      {
        id: 'mars-curiosity',
        label: 'Gale Crater region',
        description:
          'Landing region of NASA’s Curiosity rover, which found evidence that ancient lakes once filled the crater floor.',
        lat: -5,
        lon: 138,
      },
    ],
    textureKey: 'mars',
    hasAtmosphere: true,
    displayRadius: 0.7,
    orbitDistance: 16,
    color: '#c1440e',
  },

  jupiter: {
    id: 'jupiter',
    name: 'Jupiter',
    orderFromSun: 5,
    tagline: 'King of planets — a stormy gas giant',
    facts: [
      { label: 'Diameter', value: '~139,820 km (11× Earth)' },
      { label: 'Distance from Sun', value: '5.2 AU (~778 million km)' },
      { label: 'Day length', value: '~10 hours' },
      { label: 'Year length', value: '~12 Earth years' },
      { label: 'Moons', value: '95+ (incl. Io, Europa, Ganymede, Callisto)' },
      { label: 'Composition', value: 'Hydrogen & helium gas giant' },
      { label: 'Great Red Spot', value: 'Storm larger than Earth' },
      { label: 'Magnetic field', value: '~20,000× stronger than Earth’s' },
    ],
    overview:
      'Jupiter is the largest planet in the solar system — a hydrogen–helium giant with no solid surface. Banded clouds, fierce winds, and the centuries-old Great Red Spot dominate its appearance. Its gravity shaped the solar system and protects the inner planets from many comets.',
    composition:
      'Mostly hydrogen and helium with traces of ammonia, methane, and water. Under extreme pressure, hydrogen becomes metallic in the deep interior, powering a huge magnetic field. A rocky/icy core may exist deep inside.',
    notableFeatures: [
      'Great Red Spot anticyclone',
      'Rapid rotation (~10 h day)',
      'Galilean moons — mini solar system',
      'Strong magnetosphere and radiation belts',
    ],
    hotspots: [
      {
        id: 'jup-grs',
        label: 'Great Red Spot',
        description:
          'A colossal high-pressure storm larger than Earth, observed for at least 150 years and still churning today.',
        lat: -22,
        lon: -40,
      },
      {
        id: 'jup-bands',
        label: 'Cloud bands',
        description:
          'Alternating light zones and dark belts are jet streams of ammonia ice clouds driven by rapid rotation and internal heat.',
        lat: 25,
        lon: 80,
      },
      {
        id: 'jup-equator',
        label: 'Equatorial zone',
        description:
          'The brightest cloud band, where rising ammonia ice creates pale, fast-moving weather systems.',
        lat: 5,
        lon: -120,
      },
    ],
    textureKey: 'jupiter',
    hasAtmosphere: true,
    displayRadius: 2.4,
    orbitDistance: 24,
    color: '#c88b3a',
  },

  saturn: {
    id: 'saturn',
    name: 'Saturn',
    orderFromSun: 6,
    tagline: 'The jewel of the solar system — lord of the rings',
    facts: [
      { label: 'Diameter', value: '~116,460 km (9.5× Earth)' },
      { label: 'Distance from Sun', value: '9.5 AU (~1.4 billion km)' },
      { label: 'Day length', value: '~10.7 hours' },
      { label: 'Year length', value: '~29.5 Earth years' },
      { label: 'Moons', value: '140+ (incl. Titan & Enceladus)' },
      { label: 'Rings', value: 'Ice & rock particles, ~282,000 km wide' },
      { label: 'Density', value: '0.69 g/cm³ (would float in water!)' },
      { label: 'Composition', value: 'Hydrogen & helium gas giant' },
    ],
    overview:
      'Saturn is famous for its spectacular ring system — billions of ice and rock particles orbiting in thin sheets. Like Jupiter it is a gas giant, but less dense than water. Titan, its largest moon, has lakes of liquid methane; Enceladus sprays icy plumes from a subsurface ocean.',
    composition:
      'Hydrogen and helium envelope over a possible rocky/icy core. Rings are mostly water ice with some rocky dust, organized into named rings (A, B, C…) and gaps like the Cassini Division.',
    notableFeatures: [
      'Extensive ring system',
      'Lowest density of any planet',
      'Titan — thick atmosphere and methane lakes',
      'Hexagonal storm at the north pole',
    ],
    hotspots: [
      {
        id: 'sat-rings',
        label: 'Main ring system',
        description:
          'Bright A and B rings of water-ice particles, separated by the dark Cassini Division. Only tens of meters thick in places.',
        lat: 5,
        lon: 0,
      },
      {
        id: 'sat-hexagon',
        label: 'North polar hexagon',
        description:
          'A bizarre six-sided jet stream surrounding the north pole — a stable weather pattern unique to Saturn.',
        lat: 78,
        lon: 20,
      },
      {
        id: 'sat-bands',
        label: 'Atmospheric bands',
        description:
          'Pale gold and beige cloud bands of ammonia ice, stirred by winds faster than 1,800 km/h in places.',
        lat: -20,
        lon: 100,
      },
      {
        id: 'sat-cassini',
        label: 'Cassini Division',
        description:
          'A ~4,800 km gap between the A and B rings, kept relatively clear by orbital resonances with moons.',
        lat: -8,
        lon: -90,
      },
    ],
    textureKey: 'saturn',
    hasRings: true,
    hasAtmosphere: true,
    displayRadius: 2.1,
    orbitDistance: 32,
    color: '#e6c07b',
  },

  uranus: {
    id: 'uranus',
    name: 'Uranus',
    orderFromSun: 7,
    tagline: 'The sideways ice giant',
    facts: [
      { label: 'Diameter', value: '~50,724 km (4× Earth)' },
      { label: 'Distance from Sun', value: '19.2 AU (~2.9 billion km)' },
      { label: 'Day length', value: '~17 hours' },
      { label: 'Year length', value: '~84 Earth years' },
      { label: 'Moons', value: '28 (incl. Titania, Oberon, Miranda)' },
      { label: 'Tilt', value: '~98° — rolls on its side' },
      { label: 'Atmosphere', value: 'H₂, He, methane (blue-green color)' },
      { label: 'Rings', value: 'Faint dark rings' },
    ],
    overview:
      'Uranus is an ice giant that spins on its side — likely tipped by a giant ancient impact. Methane in its atmosphere absorbs red light, giving the planet a pale cyan hue. Seasons last about 21 years each because of the extreme axial tilt.',
    composition:
      'Water, ammonia, and methane ices surrounding a rocky core, with an outer hydrogen–helium atmosphere. Faint rings of dark particles orbit the equator.',
    notableFeatures: [
      'Extreme 98° axial tilt',
      'Methane-tinted cyan atmosphere',
      'Faint ring system',
      'Long, extreme seasons',
    ],
    hotspots: [
      {
        id: 'ura-poles',
        label: 'Seasonal pole',
        description:
          'During solstice one pole points almost directly at the Sun for decades, bathing that hemisphere in continuous daylight.',
        lat: 70,
        lon: 0,
      },
      {
        id: 'ura-atmosphere',
        label: 'Methane haze',
        description:
          'Methane gas absorbs red wavelengths, leaving the characteristic blue-green color of the ice giant.',
        lat: 15,
        lon: -60,
      },
      {
        id: 'ura-rings',
        label: 'Dark rings',
        description:
          'Narrow, dark rings of ice and rock dust — much fainter than Saturn’s glittering ice rings.',
        lat: -5,
        lon: 90,
      },
    ],
    textureKey: 'uranus',
    hasRings: true,
    hasAtmosphere: true,
    displayRadius: 1.5,
    orbitDistance: 40,
    color: '#7de3e0',
  },

  neptune: {
    id: 'neptune',
    name: 'Neptune',
    orderFromSun: 8,
    tagline: 'The windiest world — deep-blue ice giant',
    facts: [
      { label: 'Diameter', value: '~49,244 km (3.9× Earth)' },
      { label: 'Distance from Sun', value: '30.1 AU (~4.5 billion km)' },
      { label: 'Day length', value: '~16 hours' },
      { label: 'Year length', value: '~165 Earth years' },
      { label: 'Moons', value: '16 (incl. Triton)' },
      { label: 'Winds', value: 'Up to ~2,000 km/h — fastest in the solar system' },
      { label: 'Atmosphere', value: 'H₂, He, methane' },
      { label: 'Discovery', value: '1846 — first planet found by math prediction' },
    ],
    overview:
      'Neptune is the farthest known major planet from the Sun — a deep-blue ice giant with the strongest winds measured in the solar system. Its largest moon, Triton, orbits backwards and may be a captured Kuiper Belt object with active nitrogen geysers.',
    composition:
      'Similar to Uranus: ices of water, ammonia, and methane over a rocky core, with hydrogen–helium atmosphere tinted blue by methane. Dynamic weather includes dark storms and bright methane-ice clouds.',
    notableFeatures: [
      'Fastest winds in the solar system',
      'Great Dark Spot (Voyager-era storm)',
      'Triton — retrograde icy moon with geysers',
      'Faint ring arcs',
    ],
    hotspots: [
      {
        id: 'nep-storms',
        label: 'Storm belt',
        description:
          'Dark oval storms and bright companion clouds race through the atmosphere at extraordinary speeds.',
        lat: -25,
        lon: 50,
      },
      {
        id: 'nep-winds',
        label: 'Supersonic jets',
        description:
          'Zonal winds can exceed 2,000 km/h — faster than the speed of sound on Earth — powered by internal heat.',
        lat: 40,
        lon: -100,
      },
      {
        id: 'nep-blue',
        label: 'Methane blue',
        description:
          'Methane absorbs red light, painting Neptune a richer blue than Uranus despite similar composition.',
        lat: 5,
        lon: 140,
      },
    ],
    textureKey: 'neptune',
    hasAtmosphere: true,
    displayRadius: 1.45,
    orbitDistance: 48,
    color: '#3f54ba',
  },
}

export function getBody(id: BodyId): BodyContent {
  const body = BODIES[id]
  if (!body) {
    throw new Error(`Unknown body id: ${id}`)
  }
  return body
}

export function getAllBodies(): BodyContent[] {
  return BODY_ORDER.map((id) => BODIES[id])
}
